from ipapy import UNICODE_TO_IPA


class IpaProcessing:

    @classmethod
    def get_number2sign(cls):
        list_unique_unicodes = [
            " ",
            "a",
            "b",
            "bʲ",
            "bʲː",
            "bː",
            "d",
            "dʲ",
            "dʲː",
            "dː",
            "d͡z",
            "d͡zʲ",
            "e",
            "f",
            "fʲ",
            "fʲː",
            "i",
            "j",
            "jː",
            "k",
            "kʲ",
            "kʲː",
            "kː",
            "lʲ",
            "lʲː",
            "lˠ",
            "lˠː",
            "m",
            "mʲ",
            "mʲː",
            "mː",
            "n",
            "nʲ",
            "nʲː",
            "nː",
            "o",
            "p",
            "pʲ",
            "pʲː",
            "pː",
            "r",
            "rʲ",
            "rʲː",
            "rː",
            "s",
            "sʲ",
            "sʲː",
            "sː",
            "t",
            "tʲ",
            "tʲː",
            "tː",
            "t͡s",
            "t͡sʲ",
            "t͡sː",
            "t͡ɕ",
            "t͡ɕː",
            "u",
            "v",
            "vʲ",
            "vʲː",
            "vː",
            "x",
            "xʲ",
            "z",
            "zʲ",
            "zʲː",
            "zː",
            "æ",
            "ɐ",
            "ɕ",
            "ɕː",
            "ə",
            "ɛ",
            "ɡ",
            "ɡʲ",
            "ɡː",
            "ɨ",
            "ɪ",
            "ɵ",
            "ʂ",
            "ʂː",
            "ʈ͡ʂ",
            "ʉ",
            "ʊ",
            "ʐ",
            "ʐː",
            "ʑː",
            "ˈ",
        ]
        number2sign = dict((i, UNICODE_TO_IPA[l])
                           for i, l in enumerate(list_unique_unicodes, start=1))
        return number2sign
